{{- if .Values.carts.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: carts
  labels:
    {{- include "component.common.labels" ("carts") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
    domain: business
    extra-identifier: carts
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  selector:
    {{- include "component.common.labels" ("carts") | nindent 4 }}
{{- end }}
