{{- if .Values.carts.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  labels:
    {{- include "component.common.labels" ("carts") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "component.common.labels" ("carts") | nindent 6 }}
  template:
    metadata:
      {{- include "component.custom.annotations" .Values.carts | nindent 6 }}
      labels:
        {{- include "component.common.labels" ("carts") | nindent 8 }}
        api_service: "true"
        carts: "true"
        domain: business
        java: "true"
        job: carts
        version: '{{ .Values.carts.version }}'
    spec:
      serviceAccountName: sock-shop
      affinity:
      {{- toYaml .Values.carts.affinity | nindent 10 }}
      containers:
      - name: carts
        image: weaveworksdemos/carts:0.4.3
        env:
         - name: JAVA_OPTS
           value: {{ .Values.all.java.options }}
        resources:
        {{- toYaml .Values.carts.resources | nindent 10 }}
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          {{- if not .Values.all.securityCapabilitiesDisabled }}
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          {{- end }}
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: tmp-volume
        emptyDir:
          medium: Memory
      priorityClassName: {{ template "priority-class-name" . }}
{{- end }}
