{{- if .Values.catalogue.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    {{- include "component.common.labels" ("catalogue") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
  annotations:
  {{- toYaml .Values.catalogue.annotations | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "component.common.labels" ("catalogue") | nindent 6 }}
  template:
    metadata:
      {{- include "component.custom.annotations" .Values.catalogue | nindent 6 }}
      labels:
        {{- include "component.common.labels" ("catalogue") | nindent 8 }}
        {{- include "sock-shop.common.labels" . | nindent 8 }}
        api_service: "true"
        catalog: "true"
        domain: business
        go: "true"
        job: catalogue
    spec:
      serviceAccountName: sock-shop
      initContainers:
      - name: memory-check
        image: busybox:1.36.0
        command: ['sh', '-c', "free -h"]
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
      containers:
      - name: catalogue
        image: "{{ .Values.catalogue.image.repository }}:{{ .Values.catalogue.image.tag }}"
        args:
          - "/app"
          - "-port=8080"
        resources:
        {{- toYaml .Values.catalogue.resources | nindent 10 }}
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          readOnlyRootFilesystem: true
{{- if not .Values.all.securityCapabilitiesDisabled }}
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
{{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3
      priorityClassName: {{ template "priority-class-name" . }}
{{- end }}
