{{- if .Values.catalogue.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    {{- include "component.common.labels" ("catalogue") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
    domain: business
    extra-identifier: catalogue
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8080
  selector:
    {{- include "component.common.labels" ("catalogue") | nindent 4 }}
{{- end }}
