---
{{- if (and .Values.catalogue.demoScenarioSimulation.enabled .Values.catalogue.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-failure-script
  labels:
    {{- include "component.common.labels" ("catalogue") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
data:
  deploy-catalogue-demo-scenario.sh: |
    {{- .Files.Get "scripts/deploy-catalogue-demo-scenario.sh" | nindent 4 }}
  catalogue-failure-patch.yaml: |
    {{- .Files.Get "scripts/catalogue-failure-patch.yaml" | nindent 4 }}
  catalogue-fix-patch.yaml: |
    {{- .Files.Get "scripts/catalogue-fix-patch.yaml" | nindent 4 }}
{{- end }}
