{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    {{- include "component.common.labels" ("front-end") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
    domain: business
    extra-identifier: front-end
spec:
  ports:
  - port: 80
    targetPort: 8079
  selector:
    {{- include "component.common.labels" ("front-end") | nindent 4 }}
{{- end }}
