{{- if .Values.frontend.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    {{- include "component.common.labels" ("front-end") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "component.common.labels" ("front-end") | nindent 6 }}
  template:
    metadata:
      {{- include "component.custom.annotations" .Values.frontend | nindent 6 }}

      labels:
        {{- include "component.common.labels" ("front-end") | nindent 8 }}
        api_service: "true"
        domain: business
        frontend: "true"
        job: front-end
        nodejs: "true"
    spec:
      serviceAccountName: sock-shop
      containers:
      - name: front-end
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        resources:
        {{- toYaml .Values.frontend.resources | nindent 10 }}
        ports:
        - containerPort: 8079
        env:
        - name: SESSION_REDIS
          value: "true"
        - name: CATALOGUE_URL
          value: "http://{{.Values.frontend.components.catalogueHost}}"
        - name: TAGS_URL
          value: "http://{{.Values.frontend.components.catalogueHost}}/tags"
        - name: CARTS_URL
          value: "http://{{.Values.frontend.components.cartsHost}}/carts"
        - name: ORDERS_URL
          value: "http://{{.Values.frontend.components.ordersHost}}"
        - name: CUSTOMERS_URL
          value: "http://{{.Values.frontend.components.userHost}}/customers"
        - name: ADDRESS_URL
          value: "http://{{.Values.frontend.components.userHost}}/addresses"
        - name: CARDS_URL
          value: "http://{{.Values.frontend.components.userHost}}/cards"
        - name: LOGIN_URL
          value: "http://{{.Values.frontend.components.userHost}}/login"
        - name: REGISTER_URL
          value: "http://{{.Values.frontend.components.userHost}}/register"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: false
{{- if not .Values.all.securityCapabilitiesDisabled }}
          capabilities:
            drop:
              - all
{{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 30
          periodSeconds: 3
      priorityClassName: {{ template "priority-class-name" . }}
{{- end }}
