{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-end
  labels:
    {{- include "component.common.labels" ("front-end") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.frontend.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.frontend.ingress.ingressClassName | quote }}
  rules:
    - host: {{ (tpl .Values.frontend.ingress.hostname .) | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-end
                port:
                  number: 80
  {{- if .Values.frontend.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.frontend.ingress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.frontend.ingress.hostname }}
  {{- end }}
{{- end }}
