{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: ingress
  labels:
    {{- include "component.common.labels" ("ingress") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
spec:
  ports:
  - name: web
    port: 80
    targetPort: 8000
  - name: dashboard
    port: 8080
    targetPort: 8080
  selector:
    {{- include "component.common.labels" ("ingress") | nindent 4 }}
{{- end }}
