{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sock-shop.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: frontend
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- toYaml .Values.frontend.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.frontend.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.frontend.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-end
                port:
                  number: 80
  {{- if .Values.frontend.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.frontend.ingress.hostname }}
      secretName: {{ .Values.frontend.ingress.tlsSecretName }}
  {{- end }}
{{- end }}
