{{- if .Values.orders.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: orders-external
  labels:
    {{- include "component.common.labels" ("orders") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
    extra-identifier: orders
    domain: business
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "component.common.labels" ("orders") | nindent 4 }}
{{- end }}
