{{- if .Values.payment.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    {{- include "component.common.labels" ("payment") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
    domain: business
    extra-identifier: payment
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    {{- include "component.common.labels" ("payment") | nindent 4 }}
{{- end }}
