{{- if .Values.payment.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment
  labels:
    {{- include "component.common.labels" ("payment") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.payment.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.payment.ingress.ingressClassName | quote }}
  rules:
    - host: {{ (tpl .Values.payment.ingress.hostname .) | quote }}
      http:
        paths:
        - backend:
            service:
              name: payment
              port:
                number: 80
          path: /
          pathType: Prefix
  {{- if .Values.payment.ingress.tls  }}
  tls:
    - hosts:
        - {{ .Values.payment.ingress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.payment.ingress.hostname }}
  {{- end }}
{{- end }}
