apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ template "priority-class-name" . }}
  labels:
    {{- include "sock-shop.common.labels" . | nindent 4 }}
value: {{ .Values.priority }}
preemptionPolicy: Never
globalDefault: false
description: "Priority class for all pods of this app."
