apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: sock-shop-1000
  labels:
    {{- include "sock-shop.common.labels" . | nindent 4 }}
value: 1000
preemptionPolicy: Never
globalDefault: false
description: "Priority class for higher priority pods of this app."
