{{- if .Values.shipping.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: queue-master
  labels:
    {{- include "component.common.labels" ("queue-master") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
    domain: business
    extra-identifier: queue-master
  annotations:
    prometheus.io/path: "/prometheus"
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    {{- include "component.common.labels" ("queue-master") | nindent 4 }}
{{- end }}
