{{- if .Values.shipping.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    {{- include "component.common.labels" ("shipping") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "component.common.labels" ("shipping") | nindent 6 }}
  template:
    metadata:
      {{- include "component.custom.annotations" .Values.shipping | nindent 6 }}
      labels:
        {{- include "component.common.labels" ("shipping") | nindent 8 }}
        api_service: "true"
        domain: business
        java: "true"
        job: user
        shipping: "true"
    spec:
      serviceAccountName: sock-shop
      containers:
      - name: shipping
        image: weaveworksdemos/shipping:0.4.8
        env:
         - name: JAVA_OPTS
           value:  {{ .Values.all.java.options }}
        resources:
        {{- toYaml .Values.shipping.resources | nindent 10 }}
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          readOnlyRootFilesystem: true
          {{- if not .Values.all.securityCapabilitiesDisabled }}
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          {{- end }}
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 3
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      priorityClassName: {{ template "priority-class-name" . }}
{{- end }}
