{{- if .Values.scc.enabled }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: sock-shop-{{ .Release.Namespace }}
  labels:
    {{- include "sock-shop.common.labels" . | nindent 4 }}
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
- CHOWN
- SETGID
- SETUID
- NET_BIND_SERVICE
- DAC_OVERRIDE
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: 11
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- "system:serviceaccount:{{ .Release.Namespace }}:sock-shop"
{{- if .Values.catalogue.demoScenarioSimulation.enabled }}
- "system:serviceaccount:{{ .Release.Namespace }}:catalogue-failure-deployment"
{{- end }}
{{- range .Values.scc.extraServiceAccounts }}
- system:serviceaccount:{{ $.Release.Namespace }}:{{ . }}
{{- end }}
volumes:
- configMap
- downwardAPI
- emptyDir
- hostPath
- nfs
- persistentVolumeClaim
- projected
- secret
{{- end }}
