{{- if .Values.user.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    {{- include "component.common.labels" ("user") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "component.common.labels" ("user") | nindent 6 }}
  template:
    metadata:
      {{- include "component.custom.annotations" .Values.user | nindent 6 }}
      labels:
        {{- include "component.common.labels" ("user") | nindent 8 }}
        api_service: "true"
        domain: business
        go: "true"
        job: user
        user: "true"
    spec:
      serviceAccountName: sock-shop
      containers:
      - name: user
        image: weaveworksdemos/user:0.4.7
        resources:
        {{- toYaml .Values.user.resources | nindent 10 }}
        ports:
        - containerPort: 80
        env:
        - name: MONGO_HOST
          value: user-db:27017
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          readOnlyRootFilesystem: true
          {{- if not .Values.all.securityCapabilitiesDisabled }}
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 3
      priorityClassName: {{ template "priority-class-name" . }}
{{- end }}
