{{- if .Values.user.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  labels:
    {{- include "component.common.labels" ("user-db") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
    domain: business
    extra-identifier: user-db
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    {{- include "component.common.labels" ("user-db") | nindent 4 }}
{{- end }}
