apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sock-shop-ingress
  namespace: sock-shop
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: a65aa497c7b6648b99bebac1924e665f-400835419.us-west-2.elb.amazonaws.com  # Change this to your domain if needed
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80  # This should be the service port, which is 80
