metadata:
  labels:
    app.kubernetes.io/version: 0.3.6
  annotations:
    vcs: https://gitlab.com/stackvista/demo/microservices-demo/catalogue/-/commit/a76de6420a0d58993788a8fad3abc05d5aa39199
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 0.3.6
      annotations:
        vcs: https://gitlab.com/stackvista/demo/microservices-demo/catalogue/-/commit/a76de6420a0d58993788a8fad3abc05d5aa39199
    spec:
      containers:
        - name: catalogue
          image: quay.io/stackstate/weaveworksdemo-catalogue:0.3.6
